const users = require('./users/users.service.js');
// const taskQueue = require('./task-queue/task-queue.service.js');
const customIcons = require('./custom-icons/custom-icons.service.js');
const maestroStatus = require('./maestro-status/maestro-status.service.js');
const syslog = require('./syslog/syslog.service.js');
const blockTypes = require('./block-types/block-types.service.js');
const blockVariables = require('./block-variables/block-variables.service.js');
const blocks = require('./blocks/blocks.service.js');
const groupRoles = require('./group-roles/group-roles.service.js');
const groups = require('./groups/groups.service.js');
const organizations = require('./organizations/organizations.service.js');
const projects = require('./projects/projects.service.js');
const recordDeletions = require('./record-deletions/record-deletions.service.js');
const recordVersions = require('./record-versions/record-versions.service.js');
const requestTaskQueue = require('./request-task-queue/request-task-queue.service.js');
const requests = require('./requests/requests.service.js');
const stackResources = require('./stack-resources/stack-resources.service.js');
const stackResourceLogs = require('./stack-resource-logs/stack-resource-logs.service.js');
const roles = require('./roles/roles.service.js');
const stacks = require('./stacks/stacks.service.js');
const userRoles = require('./user-roles/user-roles.service.js');
const workflowActivities = require('./workflow-activities/workflow-activities.service.js');
const workflowBlockVariables = require('./workflow-block-variables/workflow-block-variables.service.js');
const workflowBlocks = require('./workflow-blocks/workflow-blocks.service.js');
const workflows = require('./workflows/workflows.service.js');
const rolePermissions = require('./role-permissions/role-permissions.service.js');
const groupMembers = require('./group-members/group-members.service.js');
const categories = require('./categories/categories.service.js');
const requestActivities = require('./request-activities/request-activities.service.js');
// eslint-disable-next-line no-unused-vars
module.exports = function (app) {
  app.configure(users);
  // app.configure(taskQueue);

  app.configure(customIcons);
  app.configure(maestroStatus);
  app.configure(syslog);
  app.configure(blockTypes);
  app.configure(blockVariables);
  app.configure(blocks);
  app.configure(groupRoles);
  app.configure(groups);
  app.configure(organizations);
  app.configure(projects);
  app.configure(recordDeletions);
  app.configure(recordVersions);
  app.configure(requestTaskQueue);
  app.configure(requests);
  app.configure(stackResources);
  app.configure(stackResourceLogs);
  app.configure(roles);
  app.configure(stacks);
  app.configure(userRoles);
  app.configure(workflowActivities);
  app.configure(workflowBlockVariables);
  app.configure(workflowBlocks);
  app.configure(workflows);
  app.configure(rolePermissions);
  app.configure(groupMembers);
  app.configure(categories);
  app.configure(requestActivities);
};
